# action.yml
name: 'Fixinator Action'
author: 'Foundeo Inc.'
description: 'Scans your code for CFML / ColdFusion security issues.'
inputs:
  fixinator_api_key:  # id of input
    description: 'The fixinator api key'
    required: true
    default: ''
  path:
    description: 'The file, folder, or file globber pattern to scan'
    default: '.'
  
runs:
  using: 'docker'
  image: 'docker://ghcr.io/foundeo/fixinator-docker/fixinator:latest'
  env:
    FIXINATOR_API_KEY: ${{ inputs.fixinator_api_key }}
  entrypoint: /opt/box/box
  args: 
    - fixinator
    - path=${{ inputs.path }}
    
